services:

  postgres:
    image: postgres:16-alpine
    container_name: sqlshield-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - sqlshield-network

  backend:

    build:
      context: ./backend

    container_name: sqlshield-backend

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - postgres

    networks:
      - sqlshield-network

  frontend:

    build:
      context: ./frontend

    container_name: sqlshield-frontend

    restart: unless-stopped

    depends_on:
      - backend

    networks:
      - sqlshield-network

  nginx:

    build:
      context: ./nginx

    container_name: sqlshield-nginx

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - frontend
      - backend

    networks:
      - sqlshield-network

volumes:
  postgres_data:

networks:
  sqlshield-network: